# Generated by Django 4.0.5 on 2022-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('moblie', models.IntegerField(blank=True)),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(blank=True, max_length=100)),
                ('skill3', models.CharField(blank=True, max_length=100)),
                ('skill4', models.CharField(blank=True, max_length=100)),
                ('language1', models.CharField(max_length=100)),
                ('language2', models.CharField(blank=True, max_length=100)),
                ('language3', models.CharField(blank=True, max_length=100)),
                ('work_start', models.DateField()),
                ('work_end', models.DateField()),
                ('work_experience', models.TextField()),
                ('edu_start', models.DateField()),
                ('edu_end', models.DateField()),
                ('education', models.TextField()),
            ],
        ),
    ]
