# Generated by Django 4.0.5 on 2022-06-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='edu_end',
            new_name='education_end',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='edu_start',
            new_name='education_start',
        ),
    ]
