# Generated by Django 4.0.5 on 2022-06-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_rename_edu_end_cv_education_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education_end',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education_start',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='language1',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='language2',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='language3',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='moblie',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='work_start',
        ),
    ]
